import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";
const [inputPath,outputPath]=process.argv.slice(2);if(!inputPath||!outputPath)throw new Error("Usage: node scripts/build_workbook.mjs input.json output.xlsx");
const data=JSON.parse(await fs.readFile(inputPath,"utf8")),viral=data.viral_videos||data.videos,watch=data.watchlist||[];
const wb=Workbook.create(),names=["Viral Benchmarks","Angle Radar","Campaign Territories","Watchlist","Q4 Playbook","Creators","Data Quality","Run Log"],s=Object.fromEntries(names.map(n=>[n,wb.worksheets.add(n)]));
const brown="#342A22",white="#FFFFFF",line="#DDD5CB",green="#2F6B55",amber="#F4C46C";
function title(sh,t,sub){sh.showGridLines=false;sh.getRange("A1").values=[[t]];sh.getRange("A1").format.font={bold:true,size:18,color:"#2B241F",name:"Arial"};sh.getRange("A2").values=[[sub]];sh.getRange("A2").format.font={italic:true,size:10,color:"#746A61",name:"Arial"}}
function style(sh,range,header){sh.getRange(range).format.font={name:"Arial",size:10,color:"#2B241F"};sh.getRange(range).format.borders={bottom:{style:"thin",color:line}};sh.getRange(header).format.fill=brown;sh.getRange(header).format.font={bold:true,color:white,name:"Arial",size:10};sh.getRange(header).format.wrapText=true;sh.getRange(header).format.verticalAlignment="center"}
function scores(r){r.setNumberFormat("0");r.conditionalFormats.add("colorScale",{colors:["#F4D8D2","#F5E7C8","#D9EBDD"],thresholds:["min",{type:"percentile",value:50},"max"]})}
const vb=s["Viral Benchmarks"];title(vb,"Verified Q4 gifting benchmarks",`Only posts with 10K+ likes or 1M+ views. Generated ${data.generated_at}.`);
const vh=["Tier","Likes","Views","Brand","Creator","Country","Published","Campaign territory","Strategic angle","Hook","Execution","Brand fit","Q4","Gifting","Opportunity","TikTok source"];
vb.getRange("A4:P4").values=[vh];const vr=viral.map(v=>[v.viral_tier,v.likes,v.views,v.benchmark_brand,v.creator_name,v.creator_country,v.published_at,v.campaign_territory,v.primary_angle,v.hook_summary,v.format,v.brand_fit_score,v.q4_potential_score,v.gifting_relevance_score,v.trend_score,v.canonical_url]);if(vr.length)vb.getRange("A5").write(vr);style(vb,`A4:P${4+Math.max(1,vr.length)}`,"A4:P4");vb.freezePanes.freezeRows(4);vb.getRange("B:C").setNumberFormat("#,##0");if(vr.length)scores(vb.getRange(`L5:O${4+vr.length}`));for(const [c,w] of [["A:A",13],["B:C",14],["D:G",20],["H:I",34],["J:J",58],["K:K",22],["L:O",13],["P:P",58]])vb.getRange(c).format.columnWidth=w;
const ar=s["Angle Radar"];title(ar,"Strategic angle radar","Aggregated only from viral-qualified sources. Hooks and executions are kept separate.");
ar.getRange("A4:K4").values=[["Strategic angle","Campaign territories","Viral sources","Breakout sources","Total likes","Max likes","Median opportunity","Median brand fit","Median Q4","Median gifting","Representative source"]];const rr=data.angles.map(a=>[a.angle,a.campaign_territories.join("; "),a.video_count,a.breakout_count,a.total_likes,a.max_likes,a.median_score,a.median_brand_fit,a.median_q4_potential,a.median_gifting_relevance,a.representative_url]);if(rr.length)ar.getRange("A5").write(rr);style(ar,`A4:K${4+Math.max(1,rr.length)}`,"A4:K4");ar.freezePanes.freezeRows(4);ar.getRange("E:F").setNumberFormat("#,##0");if(rr.length)scores(ar.getRange(`G5:J${4+rr.length}`));ar.getRange("A:B").format.columnWidth=38;ar.getRange("C:J").format.columnWidth=15;ar.getRange("K:K").format.columnWidth=58;
const ct=s["Campaign Territories"];title(ct,"Campaign territories","Large creative platforms that can contain multiple strategic angles, hooks and executions.");
ct.getRange("A4:D4").values=[["Campaign territory","Strategic angles observed","Viral sources","CoBa application"]];const terr=new Map();for(const v of viral){const x=terr.get(v.campaign_territory)||{a:new Set(),n:0};x.a.add(v.primary_angle);x.n++;terr.set(v.campaign_territory,x)}const tr=[...terr].map(([k,x])=>[k,[...x.a].join("; "),x.n,{ "The Gift That Proves You Know Her":"Build a handwoven bodycare ritual around one specific recipient.","Make the List Disappear":"Use tiered gifts or minis to solve multiple recipients without losing taste.","The Stocking as a Personality":"Position a CoBa mini or add-on as an aesthetic identity object.","The Ritual Gifted":"Show Unwind, Reset and Recover as a complete sensory sequence.","The Insider Edit":"Make CoBa the discovery in an expert holiday edit.","The Hard-to-Impress Recipient":"Lead with provenance and the keepsake for the woman who has everything.","Proof Before Gifting":"Earn the recommendation through texture, scent and an honest verdict."}[k]||"Adapt to approved CoBa product facts."]);if(tr.length)ct.getRange("A5").write(tr);style(ct,`A4:D${4+Math.max(1,tr.length)}`,"A4:D4");ct.getRange("A:B").format.columnWidth=42;ct.getRange("C:C").format.columnWidth=14;ct.getRange("D:D").format.columnWidth=65;ct.getRange("A4:D30").format.wrapText=true;
const wl=s["Watchlist"];title(wl,"Watchlist","Relevant references below the viral gate. Excluded from angle rankings and brief evidence.");wl.getRange("A4:H4").values=[["Likes","Views","Brand","Creator","Territory","Strategic angle","Hook","TikTok source"]];const wr=watch.map(v=>[v.likes,v.views,v.benchmark_brand,v.creator_name,v.campaign_territory,v.primary_angle,v.hook_summary,v.canonical_url]);if(wr.length)wl.getRange("A5").write(wr);style(wl,`A4:H${4+Math.max(1,wr.length)}`,"A4:H4");wl.getRange("A:B").setNumberFormat("#,##0");wl.getRange("A:F").format.columnWidth=23;wl.getRange("G:H").format.columnWidth=58;wl.getRange(`A4:H${4+Math.max(1,wr.length)}`).format.wrapText=true;
const q=s["Q4 Playbook"];title(q,"Q4 gifting playbook","Planning hypotheses for CoBa's Daughter based on verified viral patterns; not performance forecasts.");q.getRange("A4:F4").values=[["Month","Job","Priority territory","Strategic angle","Native-US hook direction","Execution"]];q.getRange("A5:F8").values=[["September","Seed discovery","The Insider Edit","Be the first to edit the season's best sets","I found the bodycare gift nobody on her list has seen yet.","Talking-head edit"],["October","Build gifting intent","The Gift That Proves You Know Her","Build a recipient-coded ritual","I'm building a bodycare gift for the friend who notices every detail.","Build-with-me"],["November","Scale utility","Make the List Disappear","Abundance that solves the whole gift list","One thoughtful ritual for every hard-to-shop-for woman on my list.","Recipient roll call"],["December","Create desire and urgency","The Hard-to-Impress Recipient","Gift the discovery she has not seen","What do you give the woman who already has everything? This.","Talking head plus keepsake reveal"]];style(q,"A4:F8","A4:F4");q.getRange("A:A").format.columnWidth=14;q.getRange("B:D").format.columnWidth=34;q.getRange("E:E").format.columnWidth=60;q.getRange("F:F").format.columnWidth=28;q.getRange("A4:F8").format.wrapText=true;
const cr=s["Creators"];title(cr,"Creator and market evidence","Country is never inferred from accent or appearance; unverified records remain labeled.");cr.getRange("A4:F4").values=[["Creator","Handle","Country","Country evidence","Viral sources","Brands featured"]];const cm=new Map();for(const v of viral){const k=v.creator_handle||v.creator_name,x=cm.get(k)||{n:v.creator_name,h:v.creator_handle,c:v.creator_country,e:v.creator_country_evidence,count:0,b:new Set()};x.count++;x.b.add(v.benchmark_brand);cm.set(k,x)}const crows=[...cm.values()].map(x=>[x.n,x.h,x.c,x.e,x.count,[...x.b].join("; ")]);if(crows.length)cr.getRange("A5").write(crows);style(cr,`A4:F${4+Math.max(1,crows.length)}`,"A4:F4");cr.getRange("A:C").format.columnWidth=22;cr.getRange("D:D").format.columnWidth=58;cr.getRange("E:F").format.columnWidth=22;
const dq=s["Data Quality"];title(dq,"Data quality","Qualification is independent from brand-fit scoring.");dq.getRange("A4:C4").values=[["Check","Count / rule","Action"]];dq.getRange("A5:C10").values=[["Viral qualification","Likes >= 10,000 OR views >= 1,000,000","Required before ranking"],["Breakout tier","Likes >= 100,000 OR views >= 3,000,000","Use as strongest pattern signal"],["Viral sources",viral.length,"Included in angle radar and briefs"],["Watchlist",watch.length,"Excluded from viral outputs"],["Missing views",viral.filter(v=>v.views==null).length,"Qualified by observed likes where available"],["Unverified creator country",viral.filter(v=>v.creator_country==="Unverified").length,"Verify before creator outreach"]];style(dq,"A4:C10","A4:C4");dq.getRange("A:A").format.columnWidth=30;dq.getRange("B:B").format.columnWidth=45;dq.getRange("C:C").format.columnWidth=55;
const rl=s["Run Log"];title(rl,"Run log","Current export metadata and definitions.");rl.getRange("A4:B4").values=[["Field","Value"]];rl.getRange("A5:B11").values=[["Generated at",new Date(data.generated_at)],["Viral-qualified sources",viral.length],["Watchlist sources",watch.length],["Viral rule",data.viral_rule.definition],["Taxonomy","Campaign territory → strategic angle → hook → execution"],["Opportunity formula","25% momentum + 30% brand fit + 25% Q4 potential + 15% gifting relevance + 5% evidence"],["Source method","Observed TikTok search metrics captured in the manual source library"]];style(rl,"A4:B11","A4:B4");rl.getRange("B5").setNumberFormat("yyyy-mm-dd hh:mm");rl.getRange("A:A").format.columnWidth=30;rl.getRange("B:B").format.columnWidth=110;rl.getRange("B:B").format.wrapText=true;
for(const sh of Object.values(s)){sh.getUsedRange()?.format.autofitRows()}
await fs.mkdir(new URL(".",`file://${outputPath}`).pathname,{recursive:true});const blob=await SpreadsheetFile.exportXlsx(wb);await blob.save(outputPath);
console.log((await wb.inspect({kind:"table",sheetId:"Viral Benchmarks",range:"A1:P12",include:"values,formulas",tableMaxRows:12,tableMaxCols:16})).ndjson);
console.log((await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:100},summary:"final formula error scan"})).ndjson);
await fs.mkdir("work/workbook-sheets",{recursive:true});for(const n of names){const img=await wb.render({sheetName:n,autoCrop:"all",scale:1});await fs.writeFile(`work/workbook-sheets/${n.toLowerCase().replaceAll(" ","-")}.png`,new Uint8Array(await img.arrayBuffer()))}
