import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const [inputPath, outputPath] = process.argv.slice(2);
if (!inputPath || !outputPath) throw new Error("Usage: node scripts/build_workbook.mjs input.json output.xlsx");
const data = JSON.parse(await fs.readFile(inputPath, "utf8"));
const wb = Workbook.create();
const names = ["Top Videos","Angle Radar","Creators","Metric History","Brand Relevance","Generated Briefs","Data Quality","Run Log"];
const sheets = Object.fromEntries(names.map(name=>[name,wb.worksheets.add(name)]));
const headerFill="#163328", headerFont="#FFFFFF", accent="#D9F99D", line="#DCE5DF";
function title(sheet,text,subtitle,cols){sheet.showGridLines=false;sheet.getRange("A1").values=[[text]];sheet.getRange("A1").format.font={bold:true,size:18,color:"#13221B",name:"Arial"};sheet.getRange("A2").values=[[subtitle]];sheet.getRange("A2").format.font={italic:true,size:10,color:"#66736C",name:"Arial"};}
function tableStyle(sheet,range,header){sheet.getRange(range).format.font={name:"Arial",size:10,color:"#13221B"};sheet.getRange(range).format.borders={bottom:{style:"thin",color:line}};sheet.getRange(header).format.fill=headerFill;sheet.getRange(header).format.font={bold:true,color:headerFont,name:"Arial",size:10};sheet.getRange(header).format.wrapText=true;}
const top=sheets["Top Videos"];title(top,"Top videos",`Generated ${data.generated_at}. ${data.is_fixture_only?"Demo fixture data — not live trend evidence.":"Verified source data."}`,"N");const vh=["Trend","Creator","Video source","Angle","Format","Hook","Views","Likes","Comments","Shares","Observed","Velocity","Relevance","Evidence"];
top.getRange("A4:N4").values=[vh];const videoRows=data.videos.map(v=>[v.trend_score,v.creator_name,v.canonical_url,v.primary_angle,v.format,v.hook_summary,v.views,v.likes,v.comments,v.shares,v.observed_at?String(v.observed_at).slice(0,16).replace("T"," "):null,v.velocity_status,v.relevance_score,v.evidence_quality]);if(videoRows.length)top.getRange("A5").write(videoRows);tableStyle(top,`A4:N${4+Math.max(1,videoRows.length)}`,"A4:N4");top.freezePanes.freezeRows(4);top.getRange("A:A").format.columnWidth=10;top.getRange("B:B").format.columnWidth=22;top.getRange("C:C").format.columnWidth=48;top.getRange("D:E").format.columnWidth=20;top.getRange("F:F").format.columnWidth=52;top.getRange("G:J").format.columnWidth=13;top.getRange("K:K").format.columnWidth=20;top.getRange("L:N").format.columnWidth=18;top.getRange("A:A").conditionalFormats.add("colorScale",{colors:["#FCE8E5","#FFF0B3",accent],thresholds:["min",{type:"percentile",value:50},"max"]});top.getRange("G:J").setNumberFormat("#,##0");
const ar=sheets["Angle Radar"];title(ar,"Angle radar","Ranked angle momentum and representative source.","E");ar.getRange("A4:E4").values=[["Angle","Videos","Median score","Max score","Representative source"]];const angleRows=data.angles.map(a=>[a.angle,a.video_count,a.median_score,a.max_score,a.representative_url]);if(angleRows.length)ar.getRange("A5").write(angleRows);tableStyle(ar,`A4:E${4+Math.max(1,angleRows.length)}`,"A4:E4");ar.freezePanes.freezeRows(4);ar.getRange("A:E").format.autofitColumns();ar.getRange("E:E").format.columnWidth=55;ar.getRange("D5:D200").conditionalFormats.add("dataBar",{color:"#1F6B4F",gradient:true});
const creators=sheets["Creators"];title(creators,"Creators","Creator market evidence and source coverage.","E");creators.getRange("A4:E4").values=[["Creator","Handle","Country","Country evidence","Videos"]];const counts=new Map();for(const v of data.videos){const k=v.creator_handle||v.creator_name;const old=counts.get(k)||{name:v.creator_name,handle:v.creator_handle,country:v.creator_country,evidence:v.creator_country_evidence,count:0};old.count++;counts.set(k,old)}const creatorRows=[...counts.values()].map(x=>[x.name,x.handle,x.country,x.evidence,x.count]);if(creatorRows.length)creators.getRange("A5").write(creatorRows);tableStyle(creators,`A4:E${4+Math.max(1,creatorRows.length)}`,"A4:E4");creators.getRange("A:E").format.autofitColumns();creators.getRange("D:D").format.columnWidth=45;
const metrics=sheets["Metric History"];title(metrics,"Metric history","Latest normalized observation in this export. SQLite preserves every snapshot.","H");metrics.getRange("A4:H4").values=[["Video ID","Observed","Views","Likes","Comments","Shares","Followers","Source"]];const metricRows=data.videos.map(v=>[v.video_id,v.observed_at?String(v.observed_at).slice(0,16).replace("T"," "):null,v.views,v.likes,v.comments,v.shares,v.followers,v.source_provider]);if(metricRows.length)metrics.getRange("A5").write(metricRows);tableStyle(metrics,`A4:H${4+Math.max(1,metricRows.length)}`,"A4:H4");metrics.getRange("A:H").format.autofitColumns();metrics.getRange("C:G").setNumberFormat("#,##0");
const relevance=sheets["Brand Relevance"];title(relevance,"Brand relevance","Trend-to-brand matching is generated in brief JSON and Markdown.","D");relevance.getRange("A4:D4").values=[["Angle","Relevance score","Representative source","Status"]];const relevanceRows=data.angles.map(a=>[a.angle,data.videos.find(v=>v.primary_angle===a.angle)?.relevance_score??null,a.representative_url,data.is_fixture_only?"Demo only":"Review"]);if(relevanceRows.length)relevance.getRange("A5").write(relevanceRows);tableStyle(relevance,`A4:D${4+Math.max(1,relevanceRows.length)}`,"A4:D4");relevance.getRange("A:D").format.autofitColumns();relevance.getRange("C:C").format.columnWidth=55;
const briefs=sheets["Generated Briefs"];title(briefs,"Generated briefs","Drafts require brand and legal approval before publishing.","F");briefs.getRange("A4:F4").values=[["Brand","Product","Generated","Brief path","Source count","Status"]];tableStyle(briefs,"A4:F5","A4:F4");briefs.getRange("A:F").format.autofitColumns();
const quality=sheets["Data Quality"];title(quality,"Data quality","Missing or unverified fields reduce scoring confidence.","C");quality.getRange("A4:C4").values=[["Check","Count","Action"]];const checks=[["Fixture records",data.videos.filter(v=>v.is_fixture).length,"Replace with verified live/manual sources"],["Missing views",data.videos.filter(v=>v.views==null).length,"Collect a new metric snapshot"],["Unverified country",data.videos.filter(v=>v.creator_country==="Unverified").length,"Add profile/provider evidence"],["Low evidence",data.videos.filter(v=>["low","fixture"].includes(v.evidence_quality)).length,"Human verification required"]];quality.getRange("A5").write(checks);tableStyle(quality,"A4:C8","A4:C4");quality.getRange("A:C").format.autofitColumns();quality.getRange("C:C").format.columnWidth=42;
const run=sheets["Run Log"];title(run,"Run log","Current export metadata.","B");run.getRange("A4:B4").values=[["Field","Value"]];run.getRange("A5:B7").values=[["Generated at",data.generated_at],["Video count",data.videos.length],["Fixture only",data.is_fixture_only]];tableStyle(run,"A4:B7","A4:B4");run.getRange("A:B").format.autofitColumns();
for(const sheet of Object.values(sheets)){sheet.getUsedRange()?.format.autofitRows();}
await fs.mkdir(new URL(".",`file://${outputPath}`).pathname,{recursive:true}).catch(()=>{});
const blob=await SpreadsheetFile.exportXlsx(wb);await blob.save(outputPath);
const inspection=await wb.inspect({kind:"table",sheetId:"Top Videos",range:"A1:N12",include:"values,formulas",tableMaxRows:12,tableMaxCols:14});console.log(inspection.ndjson);
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:100},summary:"final formula error scan"});console.log(errors.ndjson);
const preview=await wb.render({sheetName:"Top Videos",range:"A1:N9",scale:1});await fs.writeFile("work/workbook-preview.png",new Uint8Array(await preview.arrayBuffer()));
await fs.mkdir("work/workbook-sheets",{recursive:true});
for(const name of names){const rendered=await wb.render({sheetName:name,autoCrop:"all",scale:1});await fs.writeFile(`work/workbook-sheets/${name.toLowerCase().replaceAll(" ","-")}.png`,new Uint8Array(await rendered.arrayBuffer()));}
